// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddnxlywkrghydjvnfjcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkbnhseXdrcmdoeWRqdm5mamN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMTk1ODQsImV4cCI6MjA2MjU5NTU4NH0.54b-gjoOFshMyyPiNZp0bVEJT8HTnH8d3tj5YKDMVKo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);