# .github/workflows/deploy.yml

name: Deploy Vite site to GitHub Pages

on:
  push:
    branches:
      - main # Или ваша основная ветка (master, main, etc.)
  workflow_dispatch: # Позволяет запускать вручную из вкладки Actions

# Права доступа для GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Разрешить только один одновременный деплой, отменяя предыдущие запуски
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # или укажите конкретную версию, если нужно (например, "1.0.0")

      - name: Install dependencies
        run: bun install --frozen-lockfile # Используйте --frozen-lockfile для CI

      - name: Build project
        run: bun run build
        env:
          # Эта переменная будет прочитана в vite.config.ts
          BASE_URL: /700-ai-startup-ideas/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Загрузить всё из папки dist (стандартная папка сборки Vite)
          # Если вы изменили outDir в vite.config.ts, укажите здесь это имя
          path: ./dist

  deploy:
    needs: build # Зависит от успешного завершения задачи build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # URL развернутого сайта
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        # Артефакт, загруженный в job 'build' (./dist), будет автоматически использован
